
server:
  port: 8989
  context-path: /springbootday2
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.baizhi.zh.entity


